from tkinter import *
top=Tk()
name=Label(top,text="Name")
name.grid(row=0,column=0)
e1=Entry(top)
e1.grid(row=0,column=1)
password=Label(top,text="Password").grid(row=1,column=0)
e2=Entry(top)
e2.grid(row=1,column=1)
submit=Button(top,text="Submit").grid(row=2,column=1)
top.mainloop()
